// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import "package:firebase_core/firebase_core.dart" show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBu-stY8B6--WaZfyzMXF2fFMJyqsDj6gg',
    appId: '1:581643560878:web:ea99bd03019ff5fa10ca3f',
    messagingSenderId: '581643560878',
    projectId: 'rebuy-app-d23ae',
    authDomain: 'rebuy-app-d23ae.firebaseapp.com',
    storageBucket: 'rebuy-app-d23ae.firebasestorage.app',
    measurementId: 'G-PLGTTCJBPP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUVBQTJvN2Sfxz84sRJXOY2UEze8-867g',
    appId: '1:581643560878:android:20f50bd62a5a238610ca3f',
    messagingSenderId: '581643560878',
    projectId: 'rebuy-app-d23ae',
    storageBucket: 'rebuy-app-d23ae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCv-p6hF40Kl0PY8eNEvAQrckJAkYlueIk',
    appId: '1:581643560878:ios:110f4e012412dcf610ca3f',
    messagingSenderId: '581643560878',
    projectId: 'rebuy-app-d23ae',
    storageBucket: 'rebuy-app-d23ae.firebasestorage.app',
    iosBundleId: 'com.example.rebuy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCv-p6hF40Kl0PY8eNEvAQrckJAkYlueIk',
    appId: '1:581643560878:ios:110f4e012412dcf610ca3f',
    messagingSenderId: '581643560878',
    projectId: 'rebuy-app-d23ae',
    storageBucket: 'rebuy-app-d23ae.firebasestorage.app',
    iosBundleId: 'com.example.rebuy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBu-stY8B6--WaZfyzMXF2fFMJyqsDj6gg',
    appId: '1:581643560878:web:d6b12a2e650a2f2610ca3f',
    messagingSenderId: '581643560878',
    projectId: 'rebuy-app-d23ae',
    authDomain: 'rebuy-app-d23ae.firebaseapp.com',
    storageBucket: 'rebuy-app-d23ae.firebasestorage.app',
    measurementId: 'G-JQDFC4F9RH',
  );
}
